In [1]:
import pandas as pd
from pandas import read_csv
from sklearn.metrics import accuracy_score, balanced_accuracy_score, roc_auc_score, auc
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import OneHotEncoder
from numpy import argmax
import numpy as np

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

# start with linear classifiers, non-linear ones and eventually the more complex neural nets

In [2]:
# load a single file as a numpy array
# def load_file(filepath):
#     dataframe = read_csv(filepath, header=None, delim_whitespace=True)
#     return dataframe.values

# load a dataset group, such as train or test
# def load_dataset_group(group, prefix=''):
#     # load input data
#     X = load_file(prefix + group + '/X_'+group+'.txt')
#     # load class output
#     y = load_file(prefix + group + '/y_'+group+'.txt')
#     return X, y

# load the dataset, returns train and test X and y elements
# def load_dataset(prefix=''):
#     # load all train
#     trainX, trainy = load_dataset_group('train', prefix + 'HARDataset/')
#     print(trainX.shape, trainy.shape)
#     # load all test
#     testX, testy = load_dataset_group('test', prefix + 'HARDataset/')
#     print(testX.shape, testy.shape)
#     # flatten y
#     trainy, testy = trainy[:,0], testy[:,0]
#     print(trainX.shape, trainy.shape, testX.shape, testy.shape)
#     return trainX, trainy, testX, testy

# def load_dataset(prefix=''):
#     # load all train
#     train = load_dataset_group('train', prefix + 'HARDataset/')
#     print(trainX.shape, trainy.shape)
#     # load all test
#     testX, testy = load_dataset_group('test', prefix + 'HARDataset/')
#     print(testX.shape, testy.shape)
#     # flatten y
#     trainy, testy = trainy[:,0], testy[:,0]
#     print(trainX.shape, trainy.shape, testX.shape, testy.shape)
#     return trainX, trainy, testX, testy

In [3]:
# path = '../data/processed/flori5hz.csv'
# values = load_file(path)
# #X, y = load_dataset_group()
# values

In [2]:
train_df = pd.read_csv('../data/processed/train.csv')

test_df = pd.read_csv('../data/processed/test.csv')

In [3]:
X_train = train_df.drop(['state', 'name'], axis=1)
y_train = pd.DataFrame(train_df['state'])

X_test = test_df.drop(['state', 'name'], axis=1)
y_test = pd.DataFrame(test_df['state'])

print(y_test.shape)
print(test_df['state'].shape)

(1207, 1)
(1207,)


In [4]:
# create a dict of standard models to evaluate {name:object}
def define_models(models=dict()):
    # nonlinear models
#     models['knn'] = KNeighborsClassifier()
#     models['cart'] = DecisionTreeClassifier()
#    models['cart'] = { 'clf': DecisionTreeClassifier(), 'params': {}}
    #models['svm'] = SVC()
#     models['bayes'] = GaussianNB()
    # ensemble models
#     models['bag'] = BaggingClassifier(n_estimators=100)
    models['rf'] = RandomForestClassifier(n_estimators=100)
#     models['et'] = ExtraTreesClassifier(n_estimators=100)
    models['gbm'] = GradientBoostingClassifier(n_estimators=100)
#     models['bag'] = BaggingClassifier()
    #models['rf'] = { 'clf': RandomForestClassifier(n_jobs=-1), 'params': {'n_estimators': [100],
#                                                                            'bootstrap': [False],
#                                                                            'min_samples_split': [10, 20, 40, 50],
#                                                                            'max_features': ['log2', 'sqrt','auto', None], 
#                                                                           'criterion': ['entropy', 'gini']}}
#     models['et'] = ExtraTreesClassifier()
#     models['gbm'] = GradientBoostingClassifier()
    # sgd is sensitive to feature scaling
    #models['sgd'] = SGDClassifier()
    #models['gp'] = GaussianProcessClassifier()
#     models['mlp'] = MLPClassifier()
    print('Defined %d models' % len(models))
    return models

In [5]:
# get model list
models = define_models()

Defined 2 models


In [6]:
# evaluate a single model
def evaluate_model(trainX, trainy, testX, testy, model):
    # fit the model
    model.fit(trainX, trainy)
    # make predictions
    yhat = model.predict(testX)
    # evaluate predictions
    accuracy = balanced_accuracy_score(testy, yhat)
    #roc_auc = roc_auc_score(testy, yhat)
    
    print(classification_report(testy, yhat))
    print(confusion_matrix(testy, yhat))
    return accuracy * 100.0
    #return roc_auc * 100.0

# evaluate a dict of models {name:object}, returns {name:score}
def evaluate_models(trainX, trainy, testX, testy, models):
    results = dict()
    for name, model in models.items():
        # evaluate the model
        results[name] = evaluate_model(trainX, trainy, testX, testy, model)
        # show process
        print('>%s: %.3f' % (name, results[name]))
    return results

# print and plot the results
def summarize_results(results, maximize=True):
    # create a list of (name, mean(scores)) tuples
    mean_scores = [(k,v) for k,v in results.items()]
    # sort tuples by mean score
    mean_scores = sorted(mean_scores, key=lambda x: x[1])
    # reverse for descending order (e.g. for accuracy)
    if maximize:
        mean_scores = list(reversed(mean_scores))
    print()
    for name, score in mean_scores:
        print('Name=%s, Score=%.3f' % (name, score))

In [7]:
# evaluate models
results = evaluate_models(X_train, y_train, X_test, y_test, models)

/home/elizabeth/education/chair_sensor/ml_project/venv/lib/python3.5/site-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


              precision    recall  f1-score   support

           0       0.94      0.96      0.95       510
           1       0.87      0.96      0.92       533
           2       0.73      0.58      0.65        79
           3       0.89      0.36      0.52        85

    accuracy                           0.90      1207
   macro avg       0.86      0.72      0.76      1207
weighted avg       0.89      0.90      0.89      1207

[[490  12   4   4]
 [ 16 514   3   0]
 [ 12  21  46   0]
 [  3  41  10  31]]
>rf: 71.803


/home/elizabeth/education/chair_sensor/ml_project/venv/lib/python3.5/site-packages/sklearn/ensemble/gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


              precision    recall  f1-score   support

           0       0.95      0.93      0.94       510
           1       0.86      0.97      0.91       533
           2       0.69      0.59      0.64        79
           3       0.83      0.41      0.55        85

    accuracy                           0.89      1207
   macro avg       0.83      0.73      0.76      1207
weighted avg       0.88      0.89      0.88      1207

[[472  23   9   6]
 [ 13 516   4   0]
 [ 12  19  47   1]
 [  1  41   8  35]]
>gbm: 72.507


In [105]:
### summarize results
summarize_results(results)


Name=rf, Score=68.030


In [8]:
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.metrics import make_scorer, balanced_accuracy_score
from sklearn.model_selection import GridSearchCV
from pandas import DataFrame
import numpy as np

all_df = train_df.append(test_df)
all_df.reset_index(drop=True, inplace=True)

X_all = all_df.drop(['state', 'name'], axis=1)
y_all = all_df['state']

groups = all_df['name']

scorer = make_scorer(balanced_accuracy_score)

outcomes = []

def run_nested_logo(clf, params, scorer):
    logo = LeaveOneGroupOut()
    group = 0
    
    for train_index, test_index in logo.split(X_all, groups=groups):
        group += 1
        X_train, X_test = X_all.iloc[train_index], X_all.iloc[test_index]
        y_train, y_test = y_all.iloc[train_index], y_all.iloc[test_index]
        
        inner_groups = all_df.iloc[all_df.index.isin(train_index)]['name']

        logo = LeaveOneGroupOut()
        grid_obj = GridSearchCV(clf, params, scoring=scorer, cv=logo.split(X_train, groups=inner_groups), n_jobs=-1)
        grid_obj = grid_obj.fit(X_train, y_train)
        
        print(grid_obj.best_estimator_)
        clf = grid_obj.best_estimator_

        clf.fit(X_train, y_train)
        predictions = clf.predict(X_test)
        
        accuracy = balanced_accuracy_score(y_test, predictions)
        outcomes.append(accuracy)
        print("Group {0} accuracy: {1}".format(group, accuracy))
    mean_outcome = np.mean(outcomes)
    print("Mean Accuracy: {0}".format(mean_outcome))
    
def evaluate_tuned_models(models, scorer):
    results = dict()
    for name, model in models.items():
        print('>%s' % (name))
        clf, params = model['clf'], model['params']
        run_nested_logo(clf, params, scorer)

evaluate_tuned_models(models, scorer)


>rf


TypeError: list indices must be integers or slices, not str

In [21]:
# Random Forest

# random_forest = RandomForestClassifier(n_estimators=100)
# random_forest.fit(X_train, y_train)
# y_pred = random_forest.predict(X_test)
# y_pred
# acc_random_forest = round(random_forest.score(X_test, y_test) * 100, 2)

# cnt = 0
# sitting = 0
# standing = 0
# for i in range(0, len(y_pred)):
#     if not y_pred[i] == y_test[i]:
#         cnt += 1
#         if y_pred[i] == 1:
#             sitting += 1
#         else:
#             standing += 1
#         print('predicted', y_pred[i], 'actual', y_test[i])
        
# print('\nTotal:', len(y_test))
# print('Wrong:', cnt)
# print('Accuracy:', acc_random_forest)
# print('False positive:', sitting)
# print('False negative:', standing)

In [19]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import make_scorer, balanced_accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import LeaveOneGroupOut

X_train = train_df.drop(['state', 'name'], axis=1)
y_train = train_df['state']
X_test = test_df.drop(['state', 'name'], axis=1)
y_test = test_df['state']

groups = train_df['name']



logo = LeaveOneGroupOut()

# Choose the type of classifier. 
clf = RandomForestClassifier()

# clf = GradientBoostingClassifier()

depths = [2, 4, 8, 16, 32, 64, 80, 100]

# Choose some parameter combinations to try
# parameters = {'n_estimators': [100, 200],
#               'bootstrap': [False],
#               'min_samples_split': [10, 20, 40, 50],
#                'max_features': ['log2', 'sqrt','auto', None], 
#                'criterion': ['entropy', 'gini']
# #               'max_depth': depths
#              }

parameters = {'n_estimators': [100]}

# Type of scoring used to compare parameter combinations
acc_scorer = make_scorer(balanced_accuracy_score)

# Run the grid search
grid_obj = GridSearchCV(clf, parameters, scoring=acc_scorer, cv=logo.split(X_train, groups=groups), n_jobs=-1)
grid_obj = grid_obj.fit(X_train, y_train)

# Set the clf to the best combination of parameters
clf = grid_obj.best_estimator_

# Fit the best algorithm to the data. 
clf.fit(X_train, y_train)

predictions = clf.predict(X_test)
print(balanced_accuracy_score(y_test, predictions))

ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].

In [11]:
grid_obj.best_params_

{'n_estimators': 100}

In [53]:
grid_obj.best_params_

{'bootstrap': False,
 'criterion': 'gini',
 'min_samples_split': 10,
 'n_estimators': 200,
 'warm_start': False}

In [43]:
grid_obj.best_estimator_

RandomForestClassifier(bootstrap=False, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=10,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [21]:
from sklearn.model_selection import LeaveOneGroupOut
from pandas import DataFrame
import numpy as np

X_train = train_df.drop(['state', 'name'], axis=1)
y_train = train_df['state']
X_test = test_df.drop(['state', 'name'], axis=1)
y_test = test_df['state']

X_all = X_train.append(X_test)
y_all = y_train.append(y_test)

groups = train_df.append(test_df)['name']

outcomes = []

clf = RandomForestClassifier(criterion='gini',
                             max_features=None,
                             min_samples_split=5,
                             n_estimators=100)

clf = GradientBoostingClassifier(n_estimators=100)

def run_logo(clf):
    logo = LeaveOneGroupOut()
    group = 0
    
    for train_index, test_index in logo.split(X_all, groups=groups):
        group += 1
        X_train, X_test = X_all.values[train_index], X_all.values[test_index]
        y_train, y_test = y_all.values[train_index], y_all.values[test_index]
        clf.fit(X_train, y_train)
        predictions = clf.predict(X_test)
        accuracy = balanced_accuracy_score(y_test, predictions)
        outcomes.append(accuracy)
        print("Group {0} accuracy: {1}".format(group, accuracy))
    mean_outcome = np.mean(outcomes)
    print("Mean Accuracy: {0}".format(mean_outcome)) 

run_logo(clf)


Group 1 accuracy: 0.74502341311965
Group 2 accuracy: 0.7084465932863271
Group 3 accuracy: 0.4614235167312559
Group 4 accuracy: 0.5555467040971589
Group 5 accuracy: 0.47061931938279433
Group 6 accuracy: 0.8153399197516844
Group 7 accuracy: 0.722132992651308
Group 8 accuracy: 0.7543498168498168
Mean Accuracy: 0.6541102844837494


In [17]:
# testing keras neural network models
from numpy import mean
from numpy import std
from numpy import dstack
import numpy as np
from pandas import read_csv
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import LSTM
from keras.utils import to_categorical
from matplotlib import pyplot


from sklearn.metrics import classification_report

In [18]:
# load a single file as a numpy array
def load_file(filepath):
    dataframe = read_csv(filepath, header=None)
    return dataframe.values

# load a list of files and return as a 3d numpy array
def load_group(filenames, prefix=''):
    print(prefix)
    loaded = list()
    for name in filenames:
        data = load_file(prefix + name)
        loaded.append(data)
    # stack group so that features are the 3rd dimension
    #print('loaded', len(loaded[0]))
    #print('loaded', loaded)
    loaded = dstack(loaded)
    #print('stacked', loaded.shape)
    print('stacked', loaded)
    return loaded

# load a dataset group, such as train or test
def load_dataset_group(group, freq, win, overlap, prefix=''):
    filepath = prefix + '/'
    print(filepath)
    # load all 9 files as a single array
    filenames = list()
    # total acceleration
    filenames += ['total_acc_x_'+group+'_'+freq+'_'+win+'_'+overlap+'.csv', 'total_acc_y_'+group+'_'+freq+'_'+win+'_'+overlap+'.csv', 'total_acc_z_'+group+'_'+freq+'_'+win+'_'+overlap+'.csv']
#     # body acceleration
#     filenames += ['body_acc_x_'+group+'_'+win+'_'+freq+'.csv', 'body_acc_y_'+group+'_'+win+'_'+freq+'.csv', 'body_acc_z_'+group+'_'+win+'_'+freq+'.csv']
#     # body gyroscope
#     filenames += ['body_gyro_x_'+group+'_'+win+'_'+freq+'.csv', 'body_gyro_y_'+group+'_'+win+'_'+freq+'.csv', 'body_gyro_z_'+group+'_'+win+'_'+freq+'.csv']
    # load input data
    X = load_group(filenames, filepath)
    # load class output
    y = load_file(prefix + '/state_'+group+'_'+freq+'_'+win+'_'+overlap+'.csv')
    print('X:', filenames)
    print('y:', prefix + '/state_'+group+'_'+freq+'_'+win+'_'+overlap+'.csv')
    return X, y

# load the dataset, returns train and test X and y elements
def load_dataset(freq, win, overlap, prefix=''):
    # load all train
    trainX, trainy = load_dataset_group('train', freq, win, overlap, prefix)
    print(trainX.shape, trainy.shape)
    # load all test
    #testX, testy = load_dataset_group('test', freq, win, prefix)
    #print(testX.shape, testy.shape)

    # one hot encode y
    trainy = to_categorical(trainy)
#     y_true = testy
#     testy = to_categorical(testy)
#     print(trainX.shape, trainy.shape, testX.shape, testy.shape)
#     return trainX, trainy, testX, testy, y_true
    return trainX, trainy

# summarize scores
def summarize_results(scores):
    print(scores)
    m, s = mean(scores), std(scores)
    print('Accuracy: %.3f%% (+/-%.3f)' % (m, s))

In [19]:
# lstm model
# from sklearn.metrics import confusion_matrix
from keras.layers import Bidirectional

# fit and evaluate a model
def evaluate_model(trainX, trainy):
    verbose, epochs, batch_size = 1, 75, 32
    n_timesteps, n_features, n_outputs = trainX.shape[1], trainX.shape[2], trainy.shape[1]
    model = Sequential()
    model.add(LSTM(150, input_shape=(n_timesteps,n_features)))
    model.add(Dropout(0.5))
    model.add(Dense(150, activation='relu'))
    model.add(Dense(n_outputs, activation='softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['categorical_accuracy'])
    # fit network
#     model.fit(trainX, trainy, validation_split=0.2, epochs=epochs, batch_size=batch_size, verbose=verbose)
    model.fit(trainX, trainy, epochs=epochs, batch_size=batch_size, verbose=verbose)
    # evaluate model
#     _, accuracy = model.evaluate(testX, testy, batch_size=batch_size, verbose=1)
#     prediction = model.predict_classes(testX)
    return model

# run an experiment
def run_experiment(freq, win, overlap, source, repeats=1):
    # load data
    trainX, trainy = load_dataset(freq=freq, win=win, overlap=overlap, prefix=source)

    model = evaluate_model(trainX, trainy)
#     print(classification_report(y_true, pred_classes))
#     print(confusion_matrix(y_true, pred_classes))
    # summarize results
#     summarize_results(scores)
    return model

# run the experiment 
freq = '30'
win = '60'
overlap = '45'
source = '../data/processed/train/keras/done/'
model = run_experiment(freq, win, overlap, source)

../data/processed/train/keras/done//
../data/processed/train/keras/done//


W0919 12:24:02.680808 139704229000960 ag_logging.py:145] Entity <function standard_lstm at 0x7f0f0e940268> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: No module named 'tensorflow_core.contrib'
W0919 12:24:02.782994 139704229000960 ag_logging.py:145] Entity <function cudnn_lstm at 0x7f0f0e9402f0> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: No module named 'tensorflow_core.contrib'


stacked [[[-2.73437500e-02 -1.18164062e-01  9.96093750e-01]
  [-2.63671875e-02 -1.14257812e-01  9.90234375e-01]
  [-2.34375000e-02 -1.20117188e-01  9.95117188e-01]
  ...
  [-3.61328125e-02 -1.17187500e-01  9.83398438e-01]
  [-2.34375000e-02 -1.16210938e-01  9.90234375e-01]
  [-3.22265625e-02 -1.23046875e-01  9.89257812e-01]]

 [[-3.22265625e-02 -1.18164062e-01  9.90234375e-01]
  [-2.14843750e-02 -1.19140625e-01  9.95117188e-01]
  [-2.92968750e-02 -1.15234375e-01  9.84375000e-01]
  ...
  [-2.53906250e-02 -1.20117188e-01  9.88281250e-01]
  [-3.12500000e-02 -1.11328125e-01  9.84375000e-01]
  [-3.22265625e-02 -1.11328125e-01  9.93164062e-01]]

 [[-3.12500000e-02 -1.11328125e-01  9.87304688e-01]
  [-3.51562500e-02 -1.21093750e-01  9.90234375e-01]
  [-2.05078125e-02 -1.18164062e-01  9.94140625e-01]
  ...
  [-3.22265625e-02 -1.22070312e-01  9.91210938e-01]
  [-3.12500000e-02 -1.18164062e-01  9.94140625e-01]
  [-2.63671875e-02 -1.13281250e-01  9.86328125e-01]]

 ...

 [[ 8.10546875e-02 -7.8125

13741/13741 [==============================] - 21s 2ms/sample - loss: 0.1999 - categorical_accuracy: 0.9285
Epoch 47/75
13741/13741 [==============================] - 21s 1ms/sample - loss: 0.2083 - categorical_accuracy: 0.9276
Epoch 48/75
13741/13741 [==============================] - 20s 1ms/sample - loss: 0.2042 - categorical_accuracy: 0.9255
Epoch 49/75
13741/13741 [==============================] - 21s 2ms/sample - loss: 0.1981 - categorical_accuracy: 0.9322
Epoch 50/75
13741/13741 [==============================] - 20s 1ms/sample - loss: 0.1977 - categorical_accuracy: 0.9314
Epoch 51/75
13741/13741 [==============================] - 20s 1ms/sample - loss: 0.2060 - categorical_accuracy: 0.9283
Epoch 52/75
13741/13741 [==============================] - 21s 1ms/sample - loss: 0.1956 - categorical_accuracy: 0.9312
Epoch 53/75
13741/13741 [==============================] - 21s 1ms/sample - loss: 0.1831 - categorical_accuracy: 0.9343
Epoch 54/75
13741/13741 [===========================

In [21]:
## Save model to model.h5

from tensorflow.keras.models import model_from_json
import os

# Saving model
# serialize model to JSON
model_json = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("model.h5")
print("Saved model to disk")

# Loading model
json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("model.h5")
print("Loaded model from disk")

# # evaluate loaded model on test data
# loaded_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['categorical_accuracy'])
# #loaded_model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])
# # score = loaded_model.evaluate(X, Y, verbose=0)
# # print("%s: %.2f%%" % (loaded_model.metrics_names[1], score[1]*100))

# _, accuracy = model.evaluate(testX, testy, batch_size=1, verbose=1)
# print('>#%d: %.3f' % (1, accuracy))

Saved model to disk
Loaded model from disk


In [6]:
# save model and architecture to single file
model.save("model.h5")
print("Saved model to disk")

Saved model to disk


In [5]:
from keras.models import load_model
model = load_model('model.h5')

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
Use tf.cast instead.


In [1]:
# # Save model in tfjs layer format
# import tensorflowjs as tfjs

# tfjs.converters.save_keras_model(model, "./")

ImportError: No module named 'tensorflowjs'

In [63]:
# cnn-lstm model

from numpy import mean
from numpy import std
from numpy import dstack
from pandas import read_csv
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers import LSTM
from keras.layers import TimeDistributed
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from keras.utils import to_categorical
from matplotlib import pyplot

# fit and evaluate a model
def evaluate_model(trainX, trainy, testX, testy):
    # define model
    verbose, epochs, batch_size = 1, 15, 10
    n_timesteps, n_features, n_outputs = trainX.shape[1], trainX.shape[2], trainy.shape[1]
    
    #splitting windows into blocks because cnn learns features from the blocks,
    #and the window timesteps have dependencies we want to learn
    # reshape data into time steps of sub-sequences
    n_steps, n_length = 1, 50
    trainX = trainX.reshape((trainX.shape[0], n_steps, n_length, n_features))
    testX = testX.reshape((testX.shape[0], n_steps, n_length, n_features))
    # define model
    model = Sequential()
    model.add(TimeDistributed(Conv1D(filters=64, kernel_size=3, activation='relu'), input_shape=(None,n_length,n_features)))
    model.add(TimeDistributed(Conv1D(filters=64, kernel_size=3, activation='relu')))
    model.add(TimeDistributed(Dropout(0.5)))
    model.add(TimeDistributed(MaxPooling1D(pool_size=2)))
    model.add(TimeDistributed(Flatten()))
    model.add(LSTM(100))
    model.add(Dropout(0.5))
    model.add(Dense(100, activation='relu'))
    model.add(Dense(n_outputs, activation='softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['categorical_accuracy'])
    # fit network
    model.fit(trainX, trainy, epochs=epochs, batch_size=batch_size, verbose=verbose)
    # evaluate model
    _, accuracy = model.evaluate(testX, testy, batch_size=batch_size, verbose=1)
    prediction = model.predict_classes(testX)
    return prediction, accuracy

# run an experiment
def run_experiment(freq, win, repeats=1):
    # load data
    trainX, trainy, testX, testy, y_true = load_dataset(freq=freq, win=win, prefix='../data/processed/')
#     score = evaluate_model(trainX, trainy, testX, testy)
#     print(score)
    # repeat experiment
    scores = list()
    for r in range(repeats):
        pred_classes, score = evaluate_model(trainX, trainy, testX, testy)
        score = score * 100.0
        print('>#%d: %.3f' % (r+1, score))
        scores.append(score)
        print(classification_report(y_true, pred_classes))
        print(confusion_matrix(y_true, pred_classes))
    # summarize results
    summarize_results(scores)

# run the experiment
freq = '50'
win = '50'
run_experiment(freq, win)

loaded 22952
stacked (22952, 50, 3)
X: ['total_acc_x_train_50_50.csv', 'total_acc_y_train_50_50.csv', 'total_acc_z_train_50_50.csv']
y: ../data/processed/train/state_train_50_50.csv
(22952, 50, 3) (22952, 1)
loaded 4514
stacked (4514, 50, 3)
X: ['total_acc_x_test_50_50.csv', 'total_acc_y_test_50_50.csv', 'total_acc_z_test_50_50.csv']
y: ../data/processed/test/state_test_50_50.csv
(4514, 50, 3) (4514, 1)
(22952, 50, 3) (22952, 4) (4514, 50, 3) (4514, 4)
Epoch 1/15
22952/22952 [==============================] - 44s 2ms/step - loss: 0.6862 - categorical_accuracy: 0.7197
Epoch 2/15
22952/22952 [==============================] - 42s 2ms/step - loss: 0.3934 - categorical_accuracy: 0.8586
Epoch 3/15
22952/22952 [==============================] - 42s 2ms/step - loss: 0.3613 - categorical_accuracy: 0.8688
Epoch 4/15
22952/22952 [==============================] - 42s 2ms/step - loss: 0.3318 - categorical_accuracy: 0.8788
Epoch 5/15
22952/22952 [==============================] - 42s 2ms/step - lo

In [56]:
# convlstm model
from numpy import mean
from numpy import std
from numpy import dstack
from pandas import read_csv
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers import LSTM
from keras.layers import TimeDistributed
from keras.layers import ConvLSTM2D
from keras.utils import to_categorical
from matplotlib import pyplot

# fit and evaluate a model
def evaluate_model(trainX, trainy, testX, testy):
    # define model
    verbose, epochs, batch_size = 1, 15, 10
    n_timesteps, n_features, n_outputs = trainX.shape[1], trainX.shape[2], trainy.shape[1]
    # reshape into subsequences (samples, time steps, rows, cols, channels)
    n_steps, n_length = 1, 50
    trainX = trainX.reshape((trainX.shape[0], n_steps, 1, n_length, n_features))
    testX = testX.reshape((testX.shape[0], n_steps, 1, n_length, n_features))
#     print('reshaped')
#     print(trainX.shape)
    # define model
    model = Sequential()
    model.add(ConvLSTM2D(filters=64, kernel_size=(1,3), activation='relu', input_shape=(n_steps, 1, n_length, n_features)))
    model.add(Dropout(0.5))
    model.add(Flatten())
    model.add(Dense(100, activation='relu'))
    model.add(Dense(n_outputs, activation='softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['categorical_accuracy'])
    # fit network
    model.fit(trainX, trainy, epochs=epochs, batch_size=batch_size, verbose=verbose)
    # evaluate model
    _, accuracy = model.evaluate(testX, testy, batch_size=batch_size, verbose=1)
    prediction = model.predict_classes(testX)
    return prediction, accuracy

# run an experiment
def run_experiment(freq, win, repeats=1):
    # load data
    trainX, trainy, testX, testy, y_true = load_dataset(freq=freq, win=win, prefix='../data/processed/')
#     score = evaluate_model(trainX, trainy, testX, testy)
#     print(score)
    # repeat experiment
    scores = list()
    for r in range(repeats):
        pred_classes, score = evaluate_model(trainX, trainy, testX, testy)
        score = score * 100.0
        print('>#%d: %.3f' % (r+1, score))
        scores.append(score)
        print(classification_report(y_true, pred_classes))
        print(confusion_matrix(y_true, pred_classes))
    # summarize results
    summarize_results(scores)

# run the experiment
freq = '50'
win = '50'
run_experiment(freq, win)

loaded 9182
stacked (9182, 50, 3)
X: ['total_acc_x_train_50_50.csv', 'total_acc_y_train_50_50.csv', 'total_acc_z_train_50_50.csv']
y: ../data/processed/train/state_train_50_50.csv
(9182, 50, 3) (9182, 1)
loaded 1806
stacked (1806, 50, 3)
X: ['total_acc_x_test_50_50.csv', 'total_acc_y_test_50_50.csv', 'total_acc_z_test_50_50.csv']
y: ../data/processed/test/state_test_50_50.csv
(1806, 50, 3) (1806, 1)
(9182, 50, 3) (9182, 4) (1806, 50, 3) (1806, 4)
Epoch 1/15
9182/9182 [==============================] - 11s 1ms/step - loss: 1.1147 - categorical_accuracy: 0.4720
Epoch 2/15
9182/9182 [==============================] - 10s 1ms/step - loss: 0.7306 - categorical_accuracy: 0.7487
Epoch 3/15
9182/9182 [==============================] - 10s 1ms/step - loss: 0.5211 - categorical_accuracy: 0.8093
Epoch 4/15
9182/9182 [==============================] - 10s 1ms/step - loss: 0.4582 - categorical_accuracy: 0.8404
Epoch 5/15
9182/9182 [==============================] - 10s 1ms/step - loss: 0.4269 - cat