In [1]:
import pandas as pd
from pandas import read_csv
from sklearn.metrics import accuracy_score, balanced_accuracy_score, roc_auc_score, auc
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import OneHotEncoder
from numpy import argmax
import numpy as np

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

# start with linear classifiers, non-linear ones and eventually the more complex neural nets

In [2]:
# load a single file as a numpy array
# def load_file(filepath):
#     dataframe = read_csv(filepath, header=None, delim_whitespace=True)
#     return dataframe.values

# load a dataset group, such as train or test
# def load_dataset_group(group, prefix=''):
#     # load input data
#     X = load_file(prefix + group + '/X_'+group+'.txt')
#     # load class output
#     y = load_file(prefix + group + '/y_'+group+'.txt')
#     return X, y

# load the dataset, returns train and test X and y elements
# def load_dataset(prefix=''):
#     # load all train
#     trainX, trainy = load_dataset_group('train', prefix + 'HARDataset/')
#     print(trainX.shape, trainy.shape)
#     # load all test
#     testX, testy = load_dataset_group('test', prefix + 'HARDataset/')
#     print(testX.shape, testy.shape)
#     # flatten y
#     trainy, testy = trainy[:,0], testy[:,0]
#     print(trainX.shape, trainy.shape, testX.shape, testy.shape)
#     return trainX, trainy, testX, testy

# def load_dataset(prefix=''):
#     # load all train
#     train = load_dataset_group('train', prefix + 'HARDataset/')
#     print(trainX.shape, trainy.shape)
#     # load all test
#     testX, testy = load_dataset_group('test', prefix + 'HARDataset/')
#     print(testX.shape, testy.shape)
#     # flatten y
#     trainy, testy = trainy[:,0], testy[:,0]
#     print(trainX.shape, trainy.shape, testX.shape, testy.shape)
#     return trainX, trainy, testX, testy

In [3]:
# path = '../data/processed/flori5hz.csv'
# values = load_file(path)
# #X, y = load_dataset_group()
# values

In [8]:
train_df = pd.read_csv('../data/processed/train.csv')

test_df = pd.read_csv('../data/processed/test.csv')

In [9]:
X_train = train_df.drop(['state', 'name'], axis=1)
y_train = pd.DataFrame(train_df['state'])

X_test = test_df.drop(['state', 'name'], axis=1)
y_test = pd.DataFrame(test_df['state'])

print(y_test.shape)
print(test_df['state'].shape)

(6033, 1)
(6033,)


In [4]:
# create a dict of standard models to evaluate {name:object}
def define_models(models=dict()):
    # nonlinear models
#     models['knn'] = KNeighborsClassifier()
#     models['cart'] = DecisionTreeClassifier()
#    models['cart'] = { 'clf': DecisionTreeClassifier(), 'params': {}}
    #models['svm'] = SVC()
#     models['bayes'] = GaussianNB()
    # ensemble models
#     models['bag'] = BaggingClassifier(n_estimators=100)
    models['rf'] = RandomForestClassifier(n_estimators=100)
#     models['et'] = ExtraTreesClassifier(n_estimators=100)
    models['gbm'] = GradientBoostingClassifier(n_estimators=100)
#     models['bag'] = BaggingClassifier()
    #models['rf'] = { 'clf': RandomForestClassifier(n_jobs=-1), 'params': {'n_estimators': [100],
#                                                                            'bootstrap': [False],
#                                                                            'min_samples_split': [10, 20, 40, 50],
#                                                                            'max_features': ['log2', 'sqrt','auto', None], 
#                                                                           'criterion': ['entropy', 'gini']}}
#     models['et'] = ExtraTreesClassifier()
#     models['gbm'] = GradientBoostingClassifier()
    # sgd is sensitive to feature scaling
    #models['sgd'] = SGDClassifier()
    #models['gp'] = GaussianProcessClassifier()
#     models['mlp'] = MLPClassifier()
    print('Defined %d models' % len(models))
    return models

In [5]:
# get model list
models = define_models()

Defined 2 models


In [6]:
# evaluate a single model
def evaluate_model(trainX, trainy, testX, testy, model):
    # fit the model
    model.fit(trainX, trainy)
    # make predictions
    yhat = model.predict(testX)
    # evaluate predictions
    accuracy = balanced_accuracy_score(testy, yhat)
    #roc_auc = roc_auc_score(testy, yhat)
    
    print(classification_report(testy, yhat))
    print(confusion_matrix(testy, yhat))
    return accuracy * 100.0
    #return roc_auc * 100.0

# evaluate a dict of models {name:object}, returns {name:score}
def evaluate_models(trainX, trainy, testX, testy, models):
    results = dict()
    for name, model in models.items():
        # evaluate the model
        results[name] = evaluate_model(trainX, trainy, testX, testy, model)
        # show process
        print('>%s: %.3f' % (name, results[name]))
    return results

# print and plot the results
def summarize_results(results, maximize=True):
    # create a list of (name, mean(scores)) tuples
    mean_scores = [(k,v) for k,v in results.items()]
    # sort tuples by mean score
    mean_scores = sorted(mean_scores, key=lambda x: x[1])
    # reverse for descending order (e.g. for accuracy)
    if maximize:
        mean_scores = list(reversed(mean_scores))
    print()
    for name, score in mean_scores:
        print('Name=%s, Score=%.3f' % (name, score))

In [11]:
# evaluate models
results = evaluate_models(X_train, y_train, X_test, y_test, models)

/home/elizabeth/education/chair_sensor/ml_project/venv/lib/python3.5/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


              precision    recall  f1-score   support

           0       0.92      0.94      0.93      2566
           1       0.87      0.94      0.90      2661
           2       0.68      0.63      0.65       395
           3       0.89      0.42      0.57       411

   micro avg       0.88      0.88      0.88      6033
   macro avg       0.84      0.73      0.76      6033
weighted avg       0.88      0.88      0.87      6033

[[2401   97   47   21]
 [ 145 2489   27    0]
 [  49   98  247    1]
 [  18  179   43  171]]
>gbm: 72.811


/home/elizabeth/education/chair_sensor/ml_project/venv/lib/python3.5/site-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


              precision    recall  f1-score   support

           0       0.93      0.94      0.94      2566
           1       0.88      0.94      0.91      2661
           2       0.73      0.67      0.70       395
           3       0.80      0.45      0.58       411

   micro avg       0.89      0.89      0.89      6033
   macro avg       0.84      0.75      0.78      6033
weighted avg       0.89      0.89      0.89      6033

[[2420   71   31   44]
 [ 119 2507   35    0]
 [  52   79  263    1]
 [  12  183   32  184]]
>rf: 74.969


In [105]:
### summarize results
summarize_results(results)


Name=rf, Score=68.030


In [28]:
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.metrics import make_scorer, balanced_accuracy_score
from sklearn.model_selection import GridSearchCV
from pandas import DataFrame
import numpy as np

all_df = train_df.append(test_df)
all_df.reset_index(drop=True, inplace=True)

X_all = all_df.drop(['state', 'name'], axis=1)
y_all = all_df['state']

groups = all_df['name']

scorer = make_scorer(balanced_accuracy_score)

outcomes = []

def run_nested_logo(clf, params, scorer):
    logo = LeaveOneGroupOut()
    group = 0
    
    for train_index, test_index in logo.split(X_all, groups=groups):
        group += 1
        X_train, X_test = X_all.iloc[train_index], X_all.iloc[test_index]
        y_train, y_test = y_all.iloc[train_index], y_all.iloc[test_index]
        
        inner_groups = all_df.iloc[all_df.index.isin(train_index)]['name']

        logo = LeaveOneGroupOut()
        grid_obj = GridSearchCV(clf, params, scoring=scorer, cv=logo.split(X_train, groups=inner_groups), n_jobs=-1)
        grid_obj = grid_obj.fit(X_train, y_train)
        
        print(grid_obj.best_estimator_)
        clf = grid_obj.best_estimator_

        clf.fit(X_train, y_train)
        predictions = clf.predict(X_test)
        
        accuracy = balanced_accuracy_score(y_test, predictions)
        outcomes.append(accuracy)
        print("Group {0} accuracy: {1}".format(group, accuracy))
    mean_outcome = np.mean(outcomes)
    print("Mean Accuracy: {0}".format(mean_outcome))
    
def evaluate_tuned_models(models, scorer):
    results = dict()
    for name, model in models.items():
        print('>%s' % (name))
        clf, params = model['clf'], model['params']
        run_nested_logo(clf, params, scorer)

evaluate_tuned_models(models, scorer)


>bayes


TypeError: 'GaussianNB' object is not subscriptable

In [21]:
# Random Forest

# random_forest = RandomForestClassifier(n_estimators=100)
# random_forest.fit(X_train, y_train)
# y_pred = random_forest.predict(X_test)
# y_pred
# acc_random_forest = round(random_forest.score(X_test, y_test) * 100, 2)

# cnt = 0
# sitting = 0
# standing = 0
# for i in range(0, len(y_pred)):
#     if not y_pred[i] == y_test[i]:
#         cnt += 1
#         if y_pred[i] == 1:
#             sitting += 1
#         else:
#             standing += 1
#         print('predicted', y_pred[i], 'actual', y_test[i])
        
# print('\nTotal:', len(y_test))
# print('Wrong:', cnt)
# print('Accuracy:', acc_random_forest)
# print('False positive:', sitting)
# print('False negative:', standing)

In [55]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import make_scorer, balanced_accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import LeaveOneGroupOut

X_train = train_df.drop(['state', 'name'], axis=1)
y_train = train_df['state']
X_test = test_df.drop(['state', 'name'], axis=1)
y_test = test_df['state']

groups = train_df['name']



logo = LeaveOneGroupOut()

# Choose the type of classifier. 
clf = RandomForestClassifier(n_jobs=-1)

clf = GradientBoostingClassifier(n_jobs=-1)

depths = [2, 4, 8, 16, 32, 64, 80, 100]

# Choose some parameter combinations to try
# parameters = {'n_estimators': [100, 200],
#               'bootstrap': [False],
#               'min_samples_split': [10, 20, 40, 50],
#                'max_features': ['log2', 'sqrt','auto', None], 
#                'criterion': ['entropy', 'gini']
# #               'max_depth': depths
#              }

parameters = {'n_estimators': [100]}

# Type of scoring used to compare parameter combinations
acc_scorer = make_scorer(balanced_accuracy_score)

# Run the grid search
grid_obj = GridSearchCV(clf, parameters, scoring=acc_scorer, cv=logo.split(X_train, groups=groups), n_jobs=-1)
grid_obj = grid_obj.fit(X_train, y_train)

# Set the clf to the best combination of parameters
clf = grid_obj.best_estimator_

# Fit the best algorithm to the data. 
clf.fit(X_train, y_train)

predictions = clf.predict(X_test)
print(balanced_accuracy_score(y_test, predictions))

/home/elizabeth/education/chair_sensor/ml_project/venv/lib/python3.5/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


0.7017667184175723


In [53]:
grid_obj.best_params_

{'bootstrap': False,
 'criterion': 'gini',
 'min_samples_split': 10,
 'n_estimators': 200,
 'warm_start': False}

In [43]:
grid_obj.best_estimator_

RandomForestClassifier(bootstrap=False, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=10,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [43]:
from sklearn.model_selection import LeaveOneGroupOut
from pandas import DataFrame
import numpy as np

X_train = train_df.drop(['state', 'name'], axis=1)
y_train = train_df['state']
X_test = test_df.drop(['state', 'name'], axis=1)
y_test = test_df['state']

X_all = X_train.append(X_test)
y_all = y_train.append(y_test)

groups = train_df.append(test_df)['name']



outcomes = []

clf = RandomForestClassifier(criterion='gini',
                             max_features=None,
                             min_samples_split=5,
                             n_estimators=100)

#clf = GradientBoostingClassifier(n_estimators=100)

def run_logo(clf):
    logo = LeaveOneGroupOut()
    group = 0
    
    for train_index, test_index in logo.split(X_all, groups=groups):
        group += 1
        X_train, X_test = X_all.values[train_index], X_all.values[test_index]
        y_train, y_test = y_all.values[train_index], y_all.values[test_index]
        clf.fit(X_train, y_train)
        predictions = clf.predict(X_test)
        accuracy = balanced_accuracy_score(y_test, predictions)
        outcomes.append(accuracy)
        print("Group {0} accuracy: {1}".format(group, accuracy))
    mean_outcome = np.mean(outcomes)
    print("Mean Accuracy: {0}".format(mean_outcome)) 

run_logo(clf)


Group 1 accuracy: 0.7139466083621365
Group 2 accuracy: 0.7184112208713271
Group 3 accuracy: 0.639509015235235
Group 4 accuracy: 0.6918121171288931
Group 5 accuracy: 0.776493013546554
Group 6 accuracy: 0.6587910618742846
Group 7 accuracy: 0.7221768866070336
Mean Accuracy: 0.7030199890893519


In [44]:
# testing keras neural network models
from numpy import mean
from numpy import std
from numpy import dstack
import numpy as np
from pandas import read_csv
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers import LSTM
from keras.utils import to_categorical
from matplotlib import pyplot

from sklearn.metrics import classification_report

Using TensorFlow backend.


In [55]:
# load a single file as a numpy array
def load_file(filepath):
    dataframe = read_csv(filepath, header=None)
    return dataframe.values

# load a list of files and return as a 3d numpy array
def load_group(filenames, prefix=''):
    loaded = list()
    for name in filenames:
        data = load_file(prefix + name)
        loaded.append(data)
    # stack group so that features are the 3rd dimension
    print('loaded', len(loaded[0]))
    loaded = dstack(loaded)
    print('stacked', loaded.shape)
    return loaded

# load a dataset group, such as train or test
def load_dataset_group(group, freq, win, prefix=''):
    filepath = prefix + group + '/'
    # load all 9 files as a single array
    filenames = list()
    # total acceleration
    filenames += ['total_acc_x_'+group+'_'+win+'_'+freq+'.csv', 'total_acc_y_'+group+'_'+win+'_'+freq+'.csv', 'total_acc_z_'+group+'_'+win+'_'+freq+'.csv']
#     # body acceleration
#     filenames += ['body_acc_x_'+group+'_'+win+'_'+freq+'.csv', 'body_acc_y_'+group+'_'+win+'_'+freq+'.csv', 'body_acc_z_'+group+'_'+win+'_'+freq+'.csv']
#     # body gyroscope
#     filenames += ['body_gyro_x_'+group+'_'+win+'_'+freq+'.csv', 'body_gyro_y_'+group+'_'+win+'_'+freq+'.csv', 'body_gyro_z_'+group+'_'+win+'_'+freq+'.csv']
    # load input data
    X = load_group(filenames, filepath)
    # load class output
    y = load_file(prefix + group + '/state_'+group+'_'+win+'_'+freq+'.csv')
    print('X:', filenames)
    print('y:', prefix + group + '/state_'+group+'_'+win+'_'+freq+'.csv')
    return X, y

# load the dataset, returns train and test X and y elements
def load_dataset(freq, win, prefix=''):
    # load all train
    trainX, trainy = load_dataset_group('train', freq, win, prefix)
    print(trainX.shape, trainy.shape)
    # load all test
    testX, testy = load_dataset_group('test', freq, win, prefix)
    print(testX.shape, testy.shape)
    # zero-offset class values
#     trainy = trainy - 1
#     testy = testy - 1
    # one hot encode y
    trainy = to_categorical(trainy)
    y_true = testy
    testy = to_categorical(testy)
    print(trainX.shape, trainy.shape, testX.shape, testy.shape)
    return trainX, trainy, testX, testy, y_true

# summarize scores
def summarize_results(scores):
    print(scores)
    m, s = mean(scores), std(scores)
    print('Accuracy: %.3f%% (+/-%.3f)' % (m, s))

In [67]:
# lstm model
from sklearn.metrics import confusion_matrix
from keras.layers import Bidirectional

# fit and evaluate a model
def evaluate_model(trainX, trainy, testX, testy):
    verbose, epochs, batch_size = 1, 15, 10
    n_timesteps, n_features, n_outputs = trainX.shape[1], trainX.shape[2], trainy.shape[1]
    model = Sequential()
    model.add(LSTM(100, input_shape=(n_timesteps,n_features)))
    model.add(Dropout(0.5))
    model.add(Dense(100, activation='relu'))
    model.add(Dense(n_outputs, activation='softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['categorical_accuracy'])
    # fit network
    model.fit(trainX, trainy, epochs=epochs, batch_size=batch_size, verbose=verbose)
    # evaluate model
    _, accuracy = model.evaluate(testX, testy, batch_size=batch_size, verbose=1)
    prediction = model.predict_classes(testX)
    return prediction, accuracy

# run an experiment
def run_experiment(freq, win, repeats=1):
    # load data
    trainX, trainy, testX, testy, y_true = load_dataset(freq=freq, win=win, prefix='../data/processed/')
#     score = evaluate_model(trainX, trainy, testX, testy)
#     print(score)
    # repeat experiment
    scores = list()
    for r in range(repeats):
        pred_classes, score = evaluate_model(trainX, trainy, testX, testy)
        print(score)
        score = score * 100.0
        print('>#%d: %.3f' % (r+1, score))
        scores.append(score)
        print(classification_report(y_true, pred_classes))
        print(confusion_matrix(y_true, pred_classes))
    # summarize results
    summarize_results(scores)
    return pred_classes, y_true

# run the experiment
freq = '50'
win = '50'
pred_classes, y_true = run_experiment(freq, win)

loaded 23553
stacked (23553, 50, 3)
X: ['total_acc_x_train_50_50.csv', 'total_acc_y_train_50_50.csv', 'total_acc_z_train_50_50.csv']
y: ../data/processed/train/state_train_50_50.csv
(23553, 50, 3) (23553, 1)
loaded 3913
stacked (3913, 50, 3)
X: ['total_acc_x_test_50_50.csv', 'total_acc_y_test_50_50.csv', 'total_acc_z_test_50_50.csv']
y: ../data/processed/test/state_test_50_50.csv
(3913, 50, 3) (3913, 1)
(23553, 50, 3) (23553, 4) (3913, 50, 3) (3913, 4)
Epoch 1/15
23553/23553 [==============================] - 57s 2ms/step - loss: 1.1272 - categorical_accuracy: 0.4518
Epoch 2/15
23553/23553 [==============================] - 57s 2ms/step - loss: 0.9526 - categorical_accuracy: 0.6302
Epoch 3/15
23553/23553 [==============================] - 67s 3ms/step - loss: 0.7100 - categorical_accuracy: 0.7586
Epoch 4/15
23553/23553 [==============================] - 74s 3ms/step - loss: 0.4898 - categorical_accuracy: 0.8213
Epoch 5/15
23553/23553 [==============================] - 66s 3ms/step - lo

In [63]:
# cnn-lstm model

from numpy import mean
from numpy import std
from numpy import dstack
from pandas import read_csv
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers import LSTM
from keras.layers import TimeDistributed
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from keras.utils import to_categorical
from matplotlib import pyplot

# fit and evaluate a model
def evaluate_model(trainX, trainy, testX, testy):
    # define model
    verbose, epochs, batch_size = 1, 15, 10
    n_timesteps, n_features, n_outputs = trainX.shape[1], trainX.shape[2], trainy.shape[1]
    
    #splitting windows into blocks because cnn learns features from the blocks,
    #and the window timesteps have dependencies we want to learn
    # reshape data into time steps of sub-sequences
    n_steps, n_length = 1, 50
    trainX = trainX.reshape((trainX.shape[0], n_steps, n_length, n_features))
    testX = testX.reshape((testX.shape[0], n_steps, n_length, n_features))
    # define model
    model = Sequential()
    model.add(TimeDistributed(Conv1D(filters=64, kernel_size=3, activation='relu'), input_shape=(None,n_length,n_features)))
    model.add(TimeDistributed(Conv1D(filters=64, kernel_size=3, activation='relu')))
    model.add(TimeDistributed(Dropout(0.5)))
    model.add(TimeDistributed(MaxPooling1D(pool_size=2)))
    model.add(TimeDistributed(Flatten()))
    model.add(LSTM(100))
    model.add(Dropout(0.5))
    model.add(Dense(100, activation='relu'))
    model.add(Dense(n_outputs, activation='softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['categorical_accuracy'])
    # fit network
    model.fit(trainX, trainy, epochs=epochs, batch_size=batch_size, verbose=verbose)
    # evaluate model
    _, accuracy = model.evaluate(testX, testy, batch_size=batch_size, verbose=1)
    prediction = model.predict_classes(testX)
    return prediction, accuracy

# run an experiment
def run_experiment(freq, win, repeats=1):
    # load data
    trainX, trainy, testX, testy, y_true = load_dataset(freq=freq, win=win, prefix='../data/processed/')
#     score = evaluate_model(trainX, trainy, testX, testy)
#     print(score)
    # repeat experiment
    scores = list()
    for r in range(repeats):
        pred_classes, score = evaluate_model(trainX, trainy, testX, testy)
        score = score * 100.0
        print('>#%d: %.3f' % (r+1, score))
        scores.append(score)
        print(classification_report(y_true, pred_classes))
        print(confusion_matrix(y_true, pred_classes))
    # summarize results
    summarize_results(scores)

# run the experiment
freq = '50'
win = '50'
run_experiment(freq, win)

loaded 22952
stacked (22952, 50, 3)
X: ['total_acc_x_train_50_50.csv', 'total_acc_y_train_50_50.csv', 'total_acc_z_train_50_50.csv']
y: ../data/processed/train/state_train_50_50.csv
(22952, 50, 3) (22952, 1)
loaded 4514
stacked (4514, 50, 3)
X: ['total_acc_x_test_50_50.csv', 'total_acc_y_test_50_50.csv', 'total_acc_z_test_50_50.csv']
y: ../data/processed/test/state_test_50_50.csv
(4514, 50, 3) (4514, 1)
(22952, 50, 3) (22952, 4) (4514, 50, 3) (4514, 4)
Epoch 1/15
22952/22952 [==============================] - 44s 2ms/step - loss: 0.6862 - categorical_accuracy: 0.7197
Epoch 2/15
22952/22952 [==============================] - 42s 2ms/step - loss: 0.3934 - categorical_accuracy: 0.8586
Epoch 3/15
22952/22952 [==============================] - 42s 2ms/step - loss: 0.3613 - categorical_accuracy: 0.8688
Epoch 4/15
22952/22952 [==============================] - 42s 2ms/step - loss: 0.3318 - categorical_accuracy: 0.8788
Epoch 5/15
22952/22952 [==============================] - 42s 2ms/step - lo

In [56]:
# convlstm model
from numpy import mean
from numpy import std
from numpy import dstack
from pandas import read_csv
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers import LSTM
from keras.layers import TimeDistributed
from keras.layers import ConvLSTM2D
from keras.utils import to_categorical
from matplotlib import pyplot

# fit and evaluate a model
def evaluate_model(trainX, trainy, testX, testy):
    # define model
    verbose, epochs, batch_size = 1, 15, 10
    n_timesteps, n_features, n_outputs = trainX.shape[1], trainX.shape[2], trainy.shape[1]
    # reshape into subsequences (samples, time steps, rows, cols, channels)
    n_steps, n_length = 1, 50
    trainX = trainX.reshape((trainX.shape[0], n_steps, 1, n_length, n_features))
    testX = testX.reshape((testX.shape[0], n_steps, 1, n_length, n_features))
#     print('reshaped')
#     print(trainX.shape)
    # define model
    model = Sequential()
    model.add(ConvLSTM2D(filters=64, kernel_size=(1,3), activation='relu', input_shape=(n_steps, 1, n_length, n_features)))
    model.add(Dropout(0.5))
    model.add(Flatten())
    model.add(Dense(100, activation='relu'))
    model.add(Dense(n_outputs, activation='softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['categorical_accuracy'])
    # fit network
    model.fit(trainX, trainy, epochs=epochs, batch_size=batch_size, verbose=verbose)
    # evaluate model
    _, accuracy = model.evaluate(testX, testy, batch_size=batch_size, verbose=1)
    prediction = model.predict_classes(testX)
    return prediction, accuracy

# run an experiment
def run_experiment(freq, win, repeats=1):
    # load data
    trainX, trainy, testX, testy, y_true = load_dataset(freq=freq, win=win, prefix='../data/processed/')
#     score = evaluate_model(trainX, trainy, testX, testy)
#     print(score)
    # repeat experiment
    scores = list()
    for r in range(repeats):
        pred_classes, score = evaluate_model(trainX, trainy, testX, testy)
        score = score * 100.0
        print('>#%d: %.3f' % (r+1, score))
        scores.append(score)
        print(classification_report(y_true, pred_classes))
        print(confusion_matrix(y_true, pred_classes))
    # summarize results
    summarize_results(scores)

# run the experiment
freq = '50'
win = '50'
run_experiment(freq, win)

loaded 9182
stacked (9182, 50, 3)
X: ['total_acc_x_train_50_50.csv', 'total_acc_y_train_50_50.csv', 'total_acc_z_train_50_50.csv']
y: ../data/processed/train/state_train_50_50.csv
(9182, 50, 3) (9182, 1)
loaded 1806
stacked (1806, 50, 3)
X: ['total_acc_x_test_50_50.csv', 'total_acc_y_test_50_50.csv', 'total_acc_z_test_50_50.csv']
y: ../data/processed/test/state_test_50_50.csv
(1806, 50, 3) (1806, 1)
(9182, 50, 3) (9182, 4) (1806, 50, 3) (1806, 4)
Epoch 1/15
9182/9182 [==============================] - 11s 1ms/step - loss: 1.1147 - categorical_accuracy: 0.4720
Epoch 2/15
9182/9182 [==============================] - 10s 1ms/step - loss: 0.7306 - categorical_accuracy: 0.7487
Epoch 3/15
9182/9182 [==============================] - 10s 1ms/step - loss: 0.5211 - categorical_accuracy: 0.8093
Epoch 4/15
9182/9182 [==============================] - 10s 1ms/step - loss: 0.4582 - categorical_accuracy: 0.8404
Epoch 5/15
9182/9182 [==============================] - 10s 1ms/step - loss: 0.4269 - cat